name: github pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
          extended: true
      - name: pwd
        run: pwd
      - name: Build
        run: hugo --minify --destination ./public
      - name: ls
        run: ls -alR /home/runner/work/ruhrkosmos.github.io/ruhrkosmos.github.io/public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/ruhrkosmos.github.io/ruhrkosmos.github.io/public
